# syntax=docker/dockerfile:1

FROM docker.io/python:3.8

WORKDIR /mnt/code
ENV PYTHONPATH=/mnt/code

COPY data_collection/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY data_collection/ /mnt/code/data_collection

ENTRYPOINT [ "bash" ]
