name: Novo sistema publicador de diários
description: Sugerir uma nova classe base para spiders de sistemas replicáveis
title: "[Novo spider base]: Nome do sistema"
labels: ["type: spider"]
body:
  - type: input
    id: replicable-system
    attributes:
      label: URL
      description: URL da empresa ou produto que oferece o serviço de publicação
  - type: textarea
    id: replicated-systems
    attributes:
      label: Municípios replicados
      description: Adicione, no mínimo, 2 URLs de sites dos diários de prefeituras que utilizam o sistema.
      value: |
        1.
        2.
      render: bash
    validations:
      required: true
  - type: dropdown
    id: publication-format
    attributes:
      label: Formato da publicação
      description: Verifique nos 2 municípios o(s) formato(s) dos diários oficiais publicados. Selecione as opções que se aplicam
      multiple: true
      options:
        - Os diários oficiais são publicados em PDF (texto)
        - Os diários oficiais são publicados em PDF (imagem scanneada)
        - Os diários oficiais são publicados em outros formatos (ex. DOC, HTML, etc)
  - type: dropdown
    id: website-details
    attributes:
      label: Detalhes do site de publicação
      description: Selecione as opções que se aplicam
      multiple: true
      options:
        - Possui paginação
        - Possui filtro por data
        - Possui captcha
  - type: textarea
    id: additional-information
    attributes:
      label: Observações
      description: Por favor, inclua qualquer informação relevante para o desenvolvimento.
      placeholder: "Ex: outros municípios que utilizam o mesmo sistema, existência de mais de um sistema de consulta, APIs, etc."
  - type: checkboxes
    id: terms
    attributes:
      label: Não existe uma issue aberta sobre isso
      options:
        - label: Eu verifiquei e não existe uma <a href='https://github.com/okfn-brasil/querido-diario/issues'>issue aberta</a> ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo sistema.
          required: true
