# List of Spiders that are enabled to be executed
# automatically in production
SPIDERS = [
    "am_manaus",
    "al_maceio",
    "ba_salvador",
    "ba_feira_de_santana",
    "df_brasilia",
    "go_goiania",
    "ma_caxias",
    "mg_belo_horizonte",
    "ms_campo_grande",
    "pa_belem",
    "pe_jaboatao_dos_guararapes",
    "pe_petrolina",
    "pe_recife",
    "pb_joao_pessoa",
    "pi_teresina",
    "pr_curitiba",
    "pr_londrina",
    "rj_rio_de_janeiro",
    "rn_mossoro",
    "rn_natal",
    "rr_boa_vista",
    "rs_porto_alegre",
    "sc_florianopolis",
    "sp_jundiai",
    "sp_sumare",
    "to_araguaina",
    "to_palmas",
]
