name: Deploy to Scrapy Cloud

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Install shub
      run: |
        python -m pip install --upgrade pip
        pip install shub
    - name: Deploy to Scrapy Cloud
      env:
        SHUB_APIKEY: ${{ secrets.SHUB_APIKEY }}
      run: |
        cd data_collection/
        shub deploy ${{ secrets.SCRAPY_CLOUD_PROJECT_ID }}

    - name: Install project dependencies
      run: |
        cd data_collection/
        pip install -r requirements.txt

    - name: Sync spiders to API
      env:
        QUERIDODIARIO_API_URL: ${{ secrets.QUERIDODIARIO_API_URL }}
        QUERIDODIARIO_API_KEY: ${{ secrets.QUERIDODIARIO_API_KEY }}
      run: |
        cd data_collection/
        scrapy qd-sync-spiders
