name: Update spider status on production

on:
  workflow_dispatch:
    inputs:
      spider_name:
        description: 'Spider name'
        required: true
      status:
        type: choice
        description: 'New Spider status in production'
        options: 
        - enabled
        - disabled
        required: true

jobs:
  update-status:
    runs-on: ubuntu-latest
    env:
      QUERIDODIARIO_DATABASE_URL: ${{ secrets.QUERIDODIARIO_DATABASE_URL }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      with:
        python-version: '3.13'
    - name: Prepare environment
      run: |
        cd querido_diario_raspadores/
        uv sync
    - name: Enable spider in production
      if: ${{ github.event.inputs.status == 'enabled' }}
      run: |
        cd querido_diario_raspadores/
        uv run python scheduler.py enable-spider --spider_name=${{ github.event.inputs.spider_name }}
    - name: Disable spider in production
      if: ${{ github.event.inputs.status == 'disabled' }}
      run: |
        cd querido_diario_raspadores/
        uv run python scheduler.py disable-spider --spider_name=${{ github.event.inputs.spider_name }}